POST http://localhost:3000/users/register
Content-Type: application/json

{"code":"nhsk","username":"root","password":"72b289ec78e0a928c565480a435453e30acb92eddb3b78ff168b28737cf6a849","birthday":"2021-05-18","val_q":"II","val_a":"II"}

###
GET http://localhost:3000/db/id
Accept: application/json

###
GET http://localhost:3000/users/register
Content-Type: text/html

###
POST http://localhost:3000/db/delete
Content-Type: application/json

{
  "id": 2
}

###

###
GET http://localhost:3000/db/select
Accept: application/json



###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "shiroan",
  "password": "f6a3052392a62a763babb8a6389da547c25cc44e903b6f60924118f62d176f7f"
}


###

POST http://localhost:3000/users/inf
Accept: application/json
Content-Type: application/json

{"username":  "root", "req":  ["username", "password", "ID"]}

