GET http://localhost:3000/csv
Content-Type: text/csv

###
POST http://localhost:3000/db/delete
Content-Type: application/json

{
  "id": 2
}

###

###
GET http://localhost:3000/db/select
Accept: application/json



###
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "shiroan",
  "password": "f6a3052392a62a763babb8a6389da547c25cc44e903b6f60924118f62d176f7f"
}


###

POST http://localhost:3000/users/inf
Accept: application/json
Content-Type: application/json

{"username":  "root", "req":  ["username", "password", "ID"]}

